In [2]:
import sys
sys.path.append('..')

import pandas as pd
import sqlite3
import finance_data_pipeline as fp

conn = sqlite3.connect('../data/finance.db')
fp.init_db(conn)

In [23]:
sp500 = pd.read_csv('../data/sp500_companies.csv')
std = standardize_tickers(sp500, ticker_col='Symbol', name_col='Security', sector_col='GICS Sector')
batch_load_tickers(conn, std)

pd.read_sql("SELECT COUNT(*) AS n FROM tickers", conn)

Loaded 503 tickers.

     n
0  503

In [3]:
core_tickers = ["AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "JPM", "V", "JNJ"]
update_many(conn, core_tickers, interval="1d", force=True)

Fetching AAPL (1d)...
Fetching MSFT (1d)...
Fetching GOOGL (1d)...
Fetching AMZN (1d)...
Fetching NVDA (1d)...
Fetching META (1d)...
Fetching TSLA (1d)...
Fetching JPM (1d)...
Fetching V (1d)...
Fetching JNJ (1d)...

In [20]:
update_ticker_data(conn, "INTC", force=True)

Fetching INTC (1d)...

In [8]:
pd.read_sql("""
    SELECT ticker, interval, source, COUNT(*) AS bars,
           MIN(datetime) AS first_bar, MAX(datetime) AS last_bar
    FROM price_history
    GROUP BY ticker, interval, source
""", conn)

    ticker interval    source  bars   first_bar    last_bar
0        A       1d  yfinance  6724  2000-01-03  2026-09-28
1     AAPL       1d  yfinance  6724  2000-01-03  2026-09-28
2     ABBV       1d  yfinance  3455  2013-01-02  2026-09-28
3     ABNB       1d  yfinance  1455  2020-12-10  2026-09-28
4      ABT       1d  yfinance  6724  2000-01-03  2026-09-28
..     ...      ...       ...   ...         ...         ...
498    XYZ       1d  yfinance  2728  2015-11-19  2026-09-28
499    YUM       1d  yfinance  6724  2000-01-03  2026-09-28
500    ZBH       1d  yfinance  6331  2001-07-25  2026-09-28
501   ZBRA       1d  yfinance  6724  2000-01-03  2026-09-28
502    ZTS       1d  yfinance  3434  2013-02-01  2026-09-28

[503 rows x 6 columns]

In [7]:
pd.read_sql("SELECT * FROM masterlist WHERE intervals_stored IS NOT NULL", conn)

,ticker,company_name,sector,intervals_stored,sources_stored,last_updated
0,A,Agilent Technologies,Health Care,1d,yfinance,2026-09-29T21:10:20.943217
1,AAPL,Apple Inc.,Information Technology,1d,yfinance,2026-09-29T21:09:45.968226
2,ABBV,AbbVie,Health Care,1d,yfinance,2026-09-29T21:10:22.281723
3,ABNB,Airbnb,Consumer Discretionary,1d,yfinance,2026-09-29T21:10:23.122235
4,ABT,Abbott Laboratories,Health Care,1d,yfinance,2026-09-29T21:10:24.086904
...,...,...,...,...,...,...
498,XYZ,"Block, Inc.",Financials,1d,yfinance,2026-09-29T21:17:56.339249
499,YUM,Yum! Brands,Consumer Discretionary,1d,yfinance,2026-09-29T21:17:57.267387
500,ZBH,Zimmer Biomet,Health Care,1d,yfinance,2026-09-29T21:17:58.168486
501,ZBRA,Zebra Technologies,Information Technology,1d,yfinance,2026-09-29T21:17:59.031242
502,ZTS,Zoetis,Health Care,1d,yfinance,2026-09-29T21:17:59.831326

In [4]:
all_tickers = pd.read_sql("SELECT ticker FROM tickers", conn)['ticker'].tolist()
fp.update_many(conn, all_tickers, interval="15m", delay=0.5)

Fetching A (15m)...
Fetching AAPL (15m)...
Fetching ABBV (15m)...
Fetching ABNB (15m)...
Fetching ABT (15m)...
Fetching ACGL (15m)...
Fetching ACN (15m)...
Fetching ADBE (15m)...
Fetching ADI (15m)...
Fetching ADM (15m)...
Fetching ADP (15m)...
Fetching ADSK (15m)...
Fetching AEE (15m)...
Fetching AEP (15m)...
Fetching AES (15m)...
Fetching AFL (15m)...
Fetching AIG (15m)...
Fetching AIZ (15m)...
Fetching AJG (15m)...
Fetching AKAM (15m)...
Fetching ALB (15m)...
Fetching ALGN (15m)...
Fetching ALL (15m)...
Fetching ALLE (15m)...
Fetching AMAT (15m)...
Fetching AMCR (15m)...
Fetching AMD (15m)...
Fetching AME (15m)...
Fetching AMGN (15m)...
Fetching AMP (15m)...
Fetching AMT (15m)...
Fetching AMZN (15m)...
Fetching ANET (15m)...
Fetching AON (15m)...
Fetching AOS (15m)...
Fetching APA (15m)...
Fetching APD (15m)...
Fetching APH (15m)...
Fetching APO (15m)...
Fetching APP (15m)...
Fetching APTV (15m)...
Fetching ARE (15m)...
Fetching ARES (15m)...
Fetching ATO (15m)...
Fetching AVGO (15m)...
Fetching AVY (15m)...
Fetching AWK (15m)...
Fetching AXON (15m)...
Fetching AXP (15m)...
Fetching AZO (15m)...
Fetching BA (15m)...
Fetching BAC (15m)...
Fetching BALL (15m)...
Fetching BAX (15m)...
Fetching BBY (15m)...
Fetching BDX (15m)...
Fetching BE (15m)...
Fetching BEN (15m)...
Fetching BF-B (15m)...
Fetching BG (15m)...
Fetching BIIB (15m)...
Fetching BKNG (15m)...
Fetching BKR (15m)...
Fetching BLK (15m)...
Fetching BMY (15m)...
Fetching BNY (15m)...
Fetching BR (15m)...
Fetching BRK-B (15m)...
Fetching BRO (15m)...
Fetching BSX (15m)...
Fetching BX (15m)...
Fetching BXP (15m)...
Fetching C (15m)...
Fetching CAH (15m)...
Fetching CARR (15m)...
Fetching CASY (15m)...
Fetching CAT (15m)...
Fetching CB (15m)...
Fetching CBOE (15m)...
Fetching CBRE (15m)...
Fetching CCI (15m)...
Fetching CCL (15m)...
Fetching CDNS (15m)...
Fetching CDW (15m)...
Fetching CEG (15m)...
Fetching CF (15m)...
Fetching CFG (15m)...
Fetching CHD (15m)...
Fetching CHRW (15m)...
Fetching CHTR (15m)...
Fetching CI (15m)...
Fetching CIEN (15m)...
Fetching CINF (15m)...
Fetching CL (15m)...
Fetching CLX (15m)...
Fetching CMCSA (15m)...
Fetching CME (15m)...
Fetching CMG (15m)...
Fetching CMI (15m)...
Fetching CMS (15m)...
Fetching CNC (15m)...
Fetching CNP (15m)...
Fetching COF (15m)...
Fetching COHR (15m)...
Fetching COIN (15m)...
Fetching COO (15m)...
Fetching COP (15m)...
Fetching COR (15m)...
Fetching COST (15m)...
Fetching CPAY (15m)...
Fetching CPRT (15m)...
Fetching CPT (15m)...
Fetching CRH (15m)...
Fetching CRL (15m)...
Fetching CRM (15m)...
Fetching CRWD (15m)...
Fetching CSCO (15m)...
Fetching CSGP (15m)...
Fetching CSX (15m)...
Fetching CTAS (15m)...
Fetching CTSH (15m)...
Fetching CTVA (15m)...
Fetching CVNA (15m)...
Fetching CVS (15m)...
Fetching CVX (15m)...
Fetching D (15m)...
Fetching DAL (15m)...
Fetching DASH (15m)...
Fetching DD (15m)...
Fetching DDOG (15m)...
Fetching DE (15m)...
Fetching DECK (15m)...
Fetching DELL (15m)...
Fetching DG (15m)...
Fetching DGX (15m)...
Fetching DHI (15m)...
Fetching DHR (15m)...
Fetching DIS (15m)...
Fetching DLR (15m)...
Fetching DLTR (15m)...
Fetching DOC (15m)...
Fetching DOV (15m)...
Fetching DOW (15m)...
Fetching DPZ (15m)...
Fetching DRI (15m)...
Fetching DTE (15m)...
Fetching DUK (15m)...
Fetching DVA (15m)...
Fetching DVN (15m)...
Fetching DXCM (15m)...
Fetching EBAY (15m)...
Fetching ECHO (15m)...
Fetching ECL (15m)...
Fetching ED (15m)...
Fetching EFX (15m)...
Fetching EG (15m)...
Fetching EIX (15m)...
Fetching EL (15m)...
Fetching ELV (15m)...
Fetching EME (15m)...
Fetching EMR (15m)...
Fetching EOG (15m)...
Fetching EQIX (15m)...
Fetching EQT (15m)...
Fetching ERIE (15m)...
Fetching ES (15m)...
Fetching ESS (15m)...
Fetching ETN (15m)...
Fetching ETR (15m)...
Fetching EVRG (15m)...
Fetching EW (15m)...
Fetching EXC (15m)...
Fetching EXE (15m)...
Fetching EXPD (15m)...
Fetching EXPE (15m)...
Fetching EXR (15m)...
Fetching F (15m)...
Fetching FANG (15m)...
Fetching FAST (15m)...
Fetching FCX (15m)...
Fetching FDS (15m)...
Fetching FDX (15m)...
Fetching FDXF (15m)...
Fetching FE (15m)...
Fetching FERG (15m)...
Fetching FFIV (15m)...
Fetching FICO (15m)...
Fetching FIS (15m)...
Fetching FISV (15m)...
Fetching FITB (15m)...
Fetching FIX (15m)...
Fetching FLEX (15m)...
Fetching FOX (15m)...
Fetching FOXA (15m)...
Fetching FRT (15m)...
Fetching FSLR (15m)...
Fetching FTNT (15m)...
Fetching FTV (15m)...
Fetching GD (15m)...
Fetching GDDY (15m)...
Fetching GE (15m)...
Fetching GEHC (15m)...
Fetching GEN (15m)...
Fetching GEV (15m)...
Fetching GILD (15m)...
Fetching GIS (15m)...
Fetching GL (15m)...
Fetching GLW (15m)...
Fetching GM (15m)...
Fetching GNRC (15m)...
Fetching GOOG (15m)...
Fetching GOOGL (15m)...
Fetching GPC (15m)...
Fetching GPN (15m)...
Fetching GRMN (15m)...
Fetching GS (15m)...
Fetching GWW (15m)...
Fetching HAL (15m)...
Fetching HAS (15m)...
Fetching HBAN (15m)...
Fetching HCA (15m)...
Fetching HD (15m)...
Fetching HIG (15m)...
Fetching HII (15m)...
Fetching HLT (15m)...
Fetching HON (15m)...
Fetching HONA (15m)...
Fetching HOOD (15m)...
Fetching HPE (15m)...
Fetching HPQ (15m)...
Fetching HRL (15m)...
Fetching HSIC (15m)...
Fetching HST (15m)...
Fetching HSY (15m)...
Fetching HUBB (15m)...
Fetching HUM (15m)...
Fetching HWM (15m)...
Fetching IBKR (15m)...
Fetching IBM (15m)...
Fetching ICE (15m)...
Fetching IDXX (15m)...
Fetching IEX (15m)...
Fetching IFF (15m)...
Fetching ILMN (15m)...
Fetching INCY (15m)...
Fetching INTC (15m)...
Fetching INTU (15m)...
Fetching INVH (15m)...
Fetching IP (15m)...
Fetching IQV (15m)...
Fetching IR (15m)...
Fetching IRM (15m)...
Fetching ISRG (15m)...
Fetching IT (15m)...
Fetching ITW (15m)...
Fetching IVZ (15m)...
Fetching J (15m)...
Fetching JBHT (15m)...
Fetching JBL (15m)...
Fetching JCI (15m)...
Fetching JKHY (15m)...
Fetching JNJ (15m)...
Fetching JPM (15m)...
Fetching KDP (15m)...
Fetching KEY (15m)...
Fetching KEYS (15m)...
Fetching KHC (15m)...
Fetching KIM (15m)...
Fetching KKR (15m)...
Fetching KLAC (15m)...
Fetching KMB (15m)...
Fetching KMI (15m)...
Fetching KO (15m)...
Fetching KR (15m)...
Fetching KVUE (15m)...
Fetching L (15m)...
Fetching LDOS (15m)...
Fetching LEN (15m)...
Fetching LH (15m)...
Fetching LHX (15m)...
Fetching LII (15m)...
Fetching LIN (15m)...
Fetching LITE (15m)...
Fetching LLY (15m)...
Fetching LMT (15m)...
Fetching LNT (15m)...
Fetching LOW (15m)...
Fetching LRCX (15m)...
Fetching LULU (15m)...
Fetching LUV (15m)...
Fetching LVS (15m)...
Fetching LYB (15m)...
Fetching LYV (15m)...
Fetching MA (15m)...
Fetching MAA (15m)...
Fetching MAR (15m)...
Fetching MAS (15m)...
Fetching MCD (15m)...
Fetching MCHP (15m)...
Fetching MCK (15m)...
Fetching MCO (15m)...
Fetching MDLZ (15m)...
Fetching MDT (15m)...
Fetching MET (15m)...
Fetching META (15m)...
Fetching MGM (15m)...
Fetching MKC (15m)...
Fetching MLM (15m)...
Fetching MMM (15m)...
Fetching MNST (15m)...
Fetching MO (15m)...
Fetching MOS (15m)...
Fetching MPC (15m)...
Fetching MPWR (15m)...
Fetching MRK (15m)...
Fetching MRNA (15m)...
Fetching MRSH (15m)...
Fetching MRVL (15m)...
Fetching MS (15m)...
Fetching MSCI (15m)...
Fetching MSFT (15m)...
Fetching MSI (15m)...
Fetching MTB (15m)...
Fetching MTD (15m)...
Fetching MU (15m)...
Fetching NCLH (15m)...
Fetching NDAQ (15m)...
Fetching NDSN (15m)...
Fetching NEE (15m)...
Fetching NEM (15m)...
Fetching NFLX (15m)...
Fetching NI (15m)...
Fetching NKE (15m)...
Fetching NOC (15m)...
Fetching NOW (15m)...
Fetching NRG (15m)...
Fetching NSC (15m)...
Fetching NTAP (15m)...
Fetching NTRS (15m)...
Fetching NUE (15m)...
Fetching NVDA (15m)...
Fetching NVR (15m)...
Fetching NWS (15m)...
Fetching NWSA (15m)...
Fetching NXPI (15m)...
Fetching O (15m)...
Fetching ODFL (15m)...
Fetching OKE (15m)...
Fetching OMC (15m)...
Fetching ON (15m)...
Fetching ORCL (15m)...
Fetching ORLY (15m)...
Fetching OTIS (15m)...
Fetching OXY (15m)...
Fetching P (15m)...
Fetching PANW (15m)...
Fetching PAYX (15m)...
Fetching PCAR (15m)...
Fetching PCG (15m)...
Fetching PEG (15m)...
Fetching PEP (15m)...
Fetching PFE (15m)...
Fetching PFG (15m)...
Fetching PG (15m)...
Fetching PGR (15m)...
Fetching PH (15m)...
Fetching PHM (15m)...
Fetching PKG (15m)...
Fetching PLD (15m)...
Fetching PLTR (15m)...

Fetching PM (15m)...
Fetching PNC (15m)...
Fetching PNR (15m)...
Fetching PNW (15m)...
Fetching PODD (15m)...
Fetching PPG (15m)...
Fetching PPL (15m)...
Fetching PRU (15m)...
Fetching PSA (15m)...
Fetching PSKY (15m)...
Fetching PSX (15m)...
Fetching PTC (15m)...
Fetching PWR (15m)...
Fetching PYPL (15m)...
Fetching Q (15m)...
Fetching QCOM (15m)...
Fetching RCL (15m)...
Fetching RDDT (15m)...
Fetching REG (15m)...
Fetching REGN (15m)...
Fetching RF (15m)...
Fetching RJF (15m)...
Fetching RL (15m)...
Fetching RMD (15m)...
Fetching ROK (15m)...
Fetching ROL (15m)...
Fetching ROP (15m)...
Fetching ROST (15m)...
Fetching RSG (15m)...
Fetching RTX (15m)...
Fetching RVTY (15m)...
Fetching SBAC (15m)...
Fetching SBUX (15m)...
Fetching SCHW (15m)...
Fetching SHW (15m)...
Fetching SJM (15m)...
Fetching SLB (15m)...
Fetching SMCI (15m)...
Fetching SNA (15m)...
Fetching SNDK (15m)...
Fetching SNPS (15m)...
Fetching SO (15m)...
Fetching SOLV (15m)...
Fetching SPG (15m)...
Fetching SPGI (15m)...
Fetching SRE (15m)...
Fetching STE (15m)...
Fetching STLD (15m)...
Fetching STT (15m)...
Fetching STX (15m)...
Fetching STZ (15m)...
Fetching SW (15m)...
Fetching SWK (15m)...
Fetching SWKS (15m)...
Fetching SYF (15m)...
Fetching SYK (15m)...
Fetching SYY (15m)...
Fetching T (15m)...
Fetching TDG (15m)...
Fetching TDY (15m)...
Fetching TECH (15m)...
Fetching TEL (15m)...
Fetching TER (15m)...
Fetching TFC (15m)...
Fetching TGT (15m)...
Fetching TJX (15m)...
Fetching TKO (15m)...
Fetching TMO (15m)...
Fetching TMUS (15m)...
Fetching TPL (15m)...
Fetching TPR (15m)...
Fetching TRGP (15m)...
Fetching TRMB (15m)...
Fetching TROW (15m)...
Fetching TRV (15m)...
Fetching TSCO (15m)...
Fetching TSLA (15m)...
Fetching TSN (15m)...
Fetching TT (15m)...
Fetching TTWO (15m)...
Fetching TXN (15m)...
Fetching TXT (15m)...
Fetching TYL (15m)...
Fetching UAL (15m)...
Fetching UBER (15m)...
Fetching UDR (15m)...
Fetching UHS (15m)...
Fetching ULTA (15m)...
Fetching UNH (15m)...
Fetching UNP (15m)...
Fetching UPS (15m)...
Fetching URI (15m)...
Fetching USB (15m)...
Fetching V (15m)...
Fetching VEEV (15m)...
Fetching VICI (15m)...
Fetching VLO (15m)...
Fetching VLTO (15m)...
Fetching VMC (15m)...
Fetching VMRK (15m)...
Fetching VRSK (15m)...
Fetching VRSN (15m)...
Fetching VRT (15m)...
Fetching VRTX (15m)...
Fetching VST (15m)...
Fetching VTR (15m)...
Fetching VTRS (15m)...
Fetching VZ (15m)...
Fetching WAB (15m)...
Fetching WAT (15m)...
Fetching WBD (15m)...
Fetching WDAY (15m)...
Fetching WDC (15m)...
Fetching WEC (15m)...
Fetching WELL (15m)...
Fetching WFC (15m)...
Fetching WM (15m)...
Fetching WMB (15m)...
Fetching WMT (15m)...
Fetching WRB (15m)...
Fetching WSM (15m)...
Fetching WST (15m)...
Fetching WTW (15m)...
Fetching WY (15m)...
Fetching WYNN (15m)...
Fetching XEL (15m)...
Fetching XOM (15m)...
Fetching XYL (15m)...
Fetching XYZ (15m)...
Fetching YUM (15m)...
Fetching ZBH (15m)...
Fetching ZBRA (15m)...
Fetching ZTS (15m)...

In [5]:
conn.close()